name: Jest Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - run: npm ci --dev
      - run: npx eslint .
      - run: npm test
        env:
          CI: true
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_REDIRECT_URI: ${{ secrets.GH_REDIRECT_URI }}
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
